# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: integration-tests-prisma
    ports:
      - '3307:3306'
    command: ['--max_allowed_packet=32505856', '--wait-timeout=28800']
    environment:
      MYSQL_DATABASE: 'strive_test'
      MYSQL_USER: 'prisma'
      MYSQL_PASSWORD: 'prisma'
      MYSQL_ROOT_PASSWORD: 'prisma'
      MYSQL_ROOT_HOST: '%'
